name: Update JHU, NY Times, USAFacts truth data weekly
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Update truth weekly'

jobs:
  upload_zoltar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.2]

    steps:
    - run: sudo df -h
#     - run: sudo apt-get remove ansible moby-buildx libllvm8 libllvm9 libllvm10 libllvm11 linux-azure-headers-5.4.0-1040 linux-modules-5.4.0-1040-azure azure-cli google-cloud-sdk firefox ghc-9.0.1 ghc-8.10.4 adoptopenjdk-11-hotspot adoptopenjdk-8-hotspot libgl1-mesa-dri hhvm google-chrome-stable dotnet-sdk-5.0 dotnet-sdk-3.1 dotnet-runtime-5.0 dotnet-runtime-3.1 podman moby-cli llvm-11-dev llvm-10-dev llvm-9-dev llvm-8-dev powershell moby-engine mysql-server-core-8.0 mysql-client-core-8.0 snapd moby-containerd mongodb-org-server mongodb-org-mongos mongodb-org-shell
#     - run: sudo apt-get remove ghc-** azure-cli firefox google-cloud-sdk google-chrome-stable hhvm dotnet-sdk-** dotnet-runtime-** moby-** adoptopenjdk-** mongodb-org-** mysql-**
#     - run: sudo apt-get autoremove
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        
    - uses: actions/checkout@v2
      with:
        path: covid19-forecast-hub
        
    - run: sudo df -h
    
    - uses: r-lib/actions/setup-r@v1

    - name: Install system dependencies
      run: sudo apt-get install libudunits2-dev libcurl4-openssl-dev libgdal-dev
      
    - name: Checkout covidData
      uses: actions/checkout@v2
      with:
        repository: reichlab/covidData
        token: ${{secrets.TEST_TOKEN}}
        path: covidData
        
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    
    - name: Install python dependencies 
      run: pip3 install -r visualization/requirements.txt
      working-directory: ./covid19-forecast-hub
        
    - name: Install covidData R dependencies
      run: Rscript -e "install.packages(c('tidyverse', 'rvest', 'here'))"
      
    - name: Install covidHubUtils
      run: Rscript -e "install.packages('devtools');devtools::install_github('reichlab/zoltr');devtools::install_github('reichlab/covidHubUtils')"
    
    - run: sudo df -h
    - run: mkdir ./covidData/data-raw/JHU/
    
    - name: Install covidData
      run: make recent_data
      working-directory: ./covidData/code/data-processing
    - run: sudo df -h
    - name: Generate truth csv files
      run: Rscript -e 'library(covidData);library(covidHubUtils);covidHubUtils::preprocess_nytimes("./covid19-forecast-hub/data-truth/nytimes/");covidHubUtils::preprocess_usafacts("./covid19-forecast-hub/data-truth/usafacts/");covidHubUtils::preprocess_jhu("./covid19-forecast-hub/data-truth/");covidHubUtils::preprocess_hospitalization("./covid19-forecast-hub/data-truth/");covidHubUtils::save_truth_for_zoltar("./covid19-forecast-hub/data-truth/")'
        
#     - name: Create truth JSON for visualization
#       run: python3 ./data-truth/get_visualization_truth_json_from_csv.py
#       working-directory: ./covid19-forecast-hub
    - name: Push generated files to GitHub
      run: bash ./travis/push-gh.sh
      working-directory: ./covid19-forecast-hub
      env:
        GH_TOKEN: ${{secrets.TEST_TOKEN}}
    - run: sudo df -h
