name: Update JHU, NY Times, USAFacts truth data weekly
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Update truth weekly'

jobs:
  upload_zoltar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.2]

    steps:
    - run: sudo df -h
    - run: sudo apt-get purge --auto-remove azure-cli google-cloud-sdk firefox ghc-9.0.1 ghc-8.10.4 adoptopenjdk-11-hotspot
    - run: sudo df -h
#     - uses: actions/checkout@v2
#       with:
#         path: covid19-forecast-hub
#     - run: sudo df -h
#     - uses: r-lib/actions/setup-r@v1

#     - name: Install system dependencies
#       run: sudo apt-get install libudunits2-dev libcurl4-openssl-dev libgdal-dev
      
#     - name: Checkout covidData
#       uses: actions/checkout@v2
#       with:
#         repository: reichlab/covidData
#         token: ${{secrets.GH_TOKEN}}
#         path: covidData
        
#     - name: Setup Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
#         architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    
#     - name: Install python dependencies 
#       run: pip3 install -r visualization/requirements.txt
#       working-directory: ./covid19-forecast-hub
        
#     - name: Install covidData R dependencies
#       run: Rscript -e "install.packages(c('tidyverse', 'rvest', 'here'))"
      
#     - name: Install covidHubUtils
#       run: Rscript -e "install.packages('devtools');devtools::install_github('reichlab/zoltr');devtools::install_github('reichlab/covidHubUtils')"
    
#     - run: mkdir ./covidData/data-raw/JHU/
    
#     - name: Install covidData
#       run: make recent_data
#       working-directory: ./covidData/code/data-processing
      
#     - name: Generate truth csv files
#       run: Rscript -e 'library(covidData);library(covidHubUtils);covidHubUtils::preprocess_nytimes("./covid19-forecast-hub/data-truth/nytimes/");covidHubUtils::preprocess_usafacts("./covid19-forecast-hub/data-truth/usafacts/");covidHubUtils::preprocess_jhu("./covid19-forecast-hub/data-truth/");covidHubUtils::preprocess_hospitalization("./covid19-forecast-hub/data-truth/");covidHubUtils::save_truth_for_zoltar("./covid19-forecast-hub/data-truth/")'
        
#     - name: Create truth JSON for visualization
#       run: python3 ./data-truth/get_visualization_truth_json_from_csv.py
#       working-directory: ./covid19-forecast-hub
    
      
